AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Answer Corona Survey - SAM template

Resources:
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda.handler
      Runtime: nodejs12.x
      Timeout: 5
      Environment:
        Variables:
          NODE_OPTIONS: '--insecure-http-parser'
          # DYNAMODB_TABLE: !Ref Table
      # Policies:
      #   - DynamoDBCrudPolicy:
      #       TableName: !Ref Table
      Events:
        Request:
          Type: Api
          Properties:
            Path: /{path+}
            Method: any
  # Table:
  #   Type: AWS::Serverless::SimpleTable
  #   Properties:
  #     PrimaryKey:
  #       Name: tz
  #       Type: Number
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: 5
  #       WriteCapacityUnits: 5
