AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Tefillah Time REST API SAM template

Resources:
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda.handler
      Runtime: nodejs12.x
      Timeout: 10
      # Environment:
      #   Variables:
      #     DYNAMODB_TABLE: !Ref Table
      # Policies:
      #   - DynamoDBCrudPolicy:
      #       TableName: !Ref Table
      # Events:
      #   Request:
      #     Type: Api
      #     Properties:
      #       Path: /
      #       Method: any
  # Table:
  #   Type: AWS::Serverless::SimpleTable
  #   Properties:
  #     PrimaryKey:
  #       Name: SynagogueId
  #       Type: String
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: 5
  #       WriteCapacityUnits: 5
